name: Import from CVS and Build + Deploy

on:
  push:
    branches: [ cvsimport ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cvs_import:
    name: "Run CVS Import"
    runs-on: ubuntu-20.04
    outputs:
      HAS_NEW_COMMITS: ${{ steps.ifBuildTrigger.outputs.HAS_NEW_COMMITS }}

    steps:
      - name: Clone this repo to machine
        run: |
          git clone -b master https://github.com/${{ github.repository }}
          cd Radiance
          git branch -a
          git checkout cvsimport
          ls
      
      - name: Install cvsimport
        run: |
          sudo apt-get update
          sudo apt-get install git-cvs

      - name: Run CVS Import
        run: |
          cd Radiance
          bash cvsimport.sh

      - name: Set up build trigger
        id: ifBuildTrigger
        run: |
          cd Radiance
          git checkout master

          unset HAS_NEW_COMMITS
          if [[ "$(git status)" == *"Your branch is ahead of"* ]]; then HAS_NEW_COMMITS='true' ; fi
          echo set-output name=HAS_NEW_COMMITS::${HAS_NEW_COMMITS}
          echo ::set-output name=HAS_NEW_COMMITS::${HAS_NEW_COMMITS}

      - name: Push updates to master branch
        uses: ad-m/github-push-action@master
        with:
          directory: Radiance
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
        if: steps.ifBuildTrigger.outputs.HAS_NEW_COMMITS
      
  
  build_Windows:
    needs: cvs_import
    name: "Build for Windows"
    runs-on: windows-latest
    if: needs.cvs_import.outputs.HAS_NEW_COMMITS == 'true'
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash

      - name: install GnuWin32
        shell: bash
        run: |
          cd "C:/Program Files (x86)/"
          mkdir GnuWin32
          cd GnuWin32
          git clone https://github.com/leok7v/gnuwin32.mirror.git
          mv ./gnuwin32.mirror/* ./
          ls

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: 'win64_msvc2017_64'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Compile
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release --target ALL_BUILD"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true

      - name: set up QT path
        run: |
          setx path "%path%;D:\a\Radiance\Qt\5.12.8\msvc2017_64\bin"
          setx path “%path%;D:\a\Radiance\Qt\5.12.8\msvc2017_64\lib”
      - name: Build installer
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          buildWithCMakeArgs: "--config Release --target PACKAGE"
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true
      
      - name: Zip Compiled Artifact
        run: |
          mv build\_CPack_Packages\win64\NSIS\radiance-*-Windows\ radiance
          Compress-Archive -U -Path radiance\* -DestinationPath Radiance_Windows

      - name: list files
        run: |
          mkdir WindowsBuild
          cp ./build/radiance-*.exe ./WindowsBuild/Radiance_Windows.exe
          cp ./Radiance_Windows.zip ./WindowsBuild/Radiance_Windows.zip
          ls -R
        shell: bash

      - name: Zip Build Artifact
        run: |
          Compress-Archive -U -Path WindowsBuild -DestinationPath Radiance_Windows_both

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Windows_both
          path: Radiance_Windows_both.zip


  build_OSX:
    needs: cvs_import
    name: "Build for OSX"
    runs-on: macos-latest
    if: needs.cvs_import.outputs.HAS_NEW_COMMITS == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      
      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.8'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Install PackageMaker
        run: |
          mkdir PackageMaker
          cd PackageMaker
          git clone -b cvsimport https://github.com/${{ github.repository }}
          cd Radiance
          ls
          unzip -q -o PackageMaker.app.zip -d /Applications/
        shell: bash
      
      - name: Install XQuartz
        run: |
          wget https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg
          sudo installer -package /Volumes/XQuartz-2.7.11/XQuartz.pkg -target / 

      - name: Compile
        env:
          CMAKE_OSX_ARCHITECTURES: x86_64
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake ..
          make -j8

      - name: Build installer
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          export PATH=$PATH:$Qt5_DIR/lib
          sudo bash PackageMaker/Radiance/macInstall.sh

          cd build/_CPack_Packages/Darwin/PackageMaker/
          sudo cp -r ./radiance*/usr/local/radiance .
          ls
          sudo pkgbuild --identifier radiance.pkg --root "radiance" --install-location "/usr/local/radiance" radiance_Darwin.pkg
          sudo cp -r radiance_Darwin.pkg ../../../../Radiance_OSX.pkg
          du -h -d=0 *

        
      - name: Zip Build Artifact and list files
        run: |
          mkdir OSXBuild
          sudo cp Radiance_OSX.pkg ./OSXBuild/Radiance_OSX.pkg

          sudo mv ./build/_CPack_Packages/Darwin/PackageMaker/radiance-*-Darwin/usr/local/radiance ./radiance
          sudo zip -r Radiance_OSX.zip ./radiance
          sudo cp ./Radiance_OSX.zip ./OSXBuild/Radiance_OSX.zip

          sudo zip -r Radiance_OSX_both.zip ./OSXBuild
          ls -R
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_OSX_both
          path: Radiance_OSX_both.zip


  build_Linux:
    needs: cvs_import
    name: "Build for Linux"
    runs-on: ubuntu-latest
    if: needs.cvs_import.outputs.HAS_NEW_COMMITS == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      
      - name: override update version
        run: |
          git fetch
          git checkout cvsimport
          cp checkVersion.py ../checkVersion.py
          git checkout master
          cp ../checkVersion.py checkVersion.py
          python checkVersion.py
        shell: bash

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.8'

      - name: Install CMake 
        uses: ilammy/msvc-dev-cmd@v1
      

      - name: set dev packages
        run: |
          sudo apt install libglu1-mesa-dev freeglut3-dev

      - name: Compile
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j8

      - name: list files
        run: |
          cd $Qt5_DIR
          ls -R
        shell: bash

      - name: Build installer
        run: |
          export PATH=$PATH:$Qt5_DIR/bin
          export PATH=$PATH:$Qt5_DIR/lib
          cd build
          make package -j8

      - name: Zip Build Artifact
        run: |
          cd  ./build
          zip -r Radiance_Linux.zip radiance-*-Linux.tar.gz
          cp ./Radiance_Linux.zip ./../Radiance_Linux.zip
          

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Radiance_Linux
          path: Radiance_Linux.zip


  release_installers:
    needs: [build_Windows, build_OSX, build_Linux]
    name: deploy installers
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      
      - name: Download Linux installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_Linux

      - name: Download OSX installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_OSX_both
      
      - name: Download Windows installers
        uses: actions/download-artifact@v2
        with:
          name: Radiance_Windows_both

      - name: unzip artifacts
        run: |
          unzip Radiance_Linux.zip
          unzip Radiance_Windows_both.zip
          unzip Radiance_OSX_both.zip
          
      - name: Display structure of downloaded files
        run: ls -R

      - name: Get Git log
        id: get_release_note
        run: |
          LAST_COMMIT_ID=$(git log --pretty="%h" -n 1)
          RAD_VERSION=$(cat src/rt/VERSION)
          RAD_VERSION="${RAD_VERSION/RADIANCE /}"

          RELEASE_TAG="${RAD_VERSION}.${LAST_COMMIT_ID}"
          LAST_TAG=$(git describe --tags --abbrev=0)

          echo "The last tag: $LAST_TAG"
          echo "The release tag: $RELEASE_TAG"

          note_header="[<h3>$RELEASE_TAG</h3>](https://github.com/${{ github.repository }}/compare/$LAST_TAG...$RELEASE_TAG) ($(date +'%Y-%m-%d'))"
          RELEASE_NOTE="$note_header<ul>$(git log $LAST_TAG..HEAD --pretty="<li> %s -%an (%h)</li>"  )</ul>"
          echo $RELEASE_NOTE
          echo ::set-output name=RELEASE_NOTE::${RELEASE_NOTE}

      - name: get release name
        id: get_release_name
        run: |
          LAST_COMMIT_ID=$(git log --pretty="%h" -n 1)
          RAD_VERSION=$(cat src/rt/VERSION)
          RAD_VERSION="${RAD_VERSION/RADIANCE /}"

          RELEASE_TAG="${RAD_VERSION}.${LAST_COMMIT_ID}"
          RELEASE_NAME='Radiance '"${RAD_VERSION}"' ('$(date +'%Y-%m-%d')')'
          
          echo "Found Radiance version: [$RAD_VERSION]"
          echo "Release tag: $RELEASE_TAG"
          echo "Release name: $RELEASE_NAME"

          echo ::set-output name=LAST_COMMIT_ID::${LAST_COMMIT_ID}
          echo ::set-output name=RELEASE_TAG::${RELEASE_TAG}
          echo ::set-output name=RELEASE_NAME::${RELEASE_NAME}
         
      - name: check release name/note
        run: |
          echo "${{steps.get_release_name.outputs.RELEASE_TAG}}"
          echo "${{steps.get_release_name.outputs.RELEASE_NAME}}"
          echo "${{steps.get_release_note.outputs.RELEASE_NOTE}}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{steps.get_release_name.outputs.RELEASE_TAG}}
          release_name: ${{steps.get_release_name.outputs.RELEASE_NAME}}
          commitish: master
          body: ${{steps.get_release_note.outputs.RELEASE_NOTE}}
          draft: false
          prerelease: true
      
      - name: Release Asset Radiance_Windows exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: WindowsBuild/Radiance_Windows.exe
          asset_name: Radiance_${{steps.get_release_name.outputs.RELEASE_TAG}}_Windows.exe
          asset_content_type: application/exe
      
      - name: Release Asset Radiance_Windows zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: WindowsBuild/Radiance_Windows.zip
          asset_name: Radiance_${{steps.get_release_name.outputs.RELEASE_TAG}}_Windows.zip
          asset_content_type: application/zip

      - name: Release Asset Radiance_Linux
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: Radiance_Linux.zip
          asset_name: Radiance_${{steps.get_release_name.outputs.RELEASE_TAG}}_Linux.zip
          asset_content_type: application/zip
      
      - name: Release Asset Radiance_OSX pkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: OSXBuild/Radiance_OSX.pkg
          asset_name: Radiance_${{steps.get_release_name.outputs.RELEASE_TAG}}_OSX.pkg
          asset_content_type: application/pkg

      - name: Release Asset Radiance_OSX zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: OSXBuild/Radiance_OSX.zip
          asset_name: Radiance_${{steps.get_release_name.outputs.RELEASE_TAG}}_OSX.zip
          asset_content_type: application/zip
